

spring:
  application:
    name: hm
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hm?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456?
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: false
  params: count=countSql
  pageSizeZero: true
  auto-dialect: false
  auto-runtime-dialect: false

server:
  port: 9001